### ISSUE TITLE
Wrap examples with inline code

### ISSUE THREAD

**Issue by herpiko** [ivanlanin/puebi#2]
![screen shot 2016-07-03 at 11 20 44 am](https://cloud.githubusercontent.com/assets/2534060/16543743/70a4b1dc-4110-11e6-9090-5503299a3ee8.png)

@ivanlanin, It makes clearer, whether it is an example or general texts. If you are agreed, I'll send the PR.

**Comment by herpiko** [comment]
It could be applied to specific word like the pict bellow. More readable than `huruf q dan x khusus digunakan...` sentence. 

![screen shot 2016-07-03 at 11 27 19 am](https://cloud.githubusercontent.com/assets/2534060/16543749/3c2e5e8e-4111-11e6-94ad-434f2d11667d.png)

**Comment by ivanlanin** [comment]
Menarik. Terima kasih. Saya pikirkan dulu sebentar.
Ngomong-ngomong, sudah unduh PDF aslinya? http://badanbahasa.kemdikbud.go.id/lamanbahasa/sites/default/files/permendikbud%20nomor%2050%20tahun%202015.pdf

**Comment by herpiko** [comment]
Tidak ditemukan.

![screen shot 2016-07-03 at 11 32 17 am](https://cloud.githubusercontent.com/assets/2534060/16543753/d45a47ea-4111-11e6-9f71-89e880698c31.png)

Eh di sini berbahasa Indonesia, ya? Maafkan saya, Bapak. 😅  /_dijewer_

**Comment by ivanlanin** [comment]
Duh, iya, jadi nggak ada. Ini cadangannya: https://upload.wikimedia.org/wikipedia/commons/3/33/Peraturan_Menteri_Pendidikan_dan_Kebudayaan_Nomor_50_Tahun_2015_tentang_Pedoman_Umum_Ejaan_Bahasa_Indonesia.pdf

Bahasa Indonesia aja. Proyeknya sendirikan tentang bahasa Indonesia 😊

**Comment by ivanlanin** [comment]
Saya pikir kita pakai huruf miring saja.
