### ISSUE TITLE
Rapikan halaman Penulisan Unsur Serapan

### ISSUE THREAD

**Issue by herpiko** [ivanlanin/puebi#6]

**Comment by herpiko** [comment]
Mohon di-_assign_ ke saya agar tidak konflik. 😄

**Comment by ivanlanin** [comment]
Silakan. Mungkin kita perlu pecah laman-lamannya untuk memudahkan pembagian.

**Comment by mughnimind** [comment]
Om, itu aku udah mbenahin halaman 'Penulisan Unsur Serapan', mohon di tanggapi. #9

Karena bahkan saya sendiri kurang paham bagaimana sistem kolaborasi pada Github.


_Sent from my Xiaomi 2014813 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ivanlanin** [comment]
Terima kasih banyak, @mughnimind. Isu ini saya tutup, ya.
