### ISSUE TITLE
— dan – itu Berbeda

### ISSUE THREAD

**Issue by taufik-nurrohman** [ivanlanin/puebi#8]
— atau M-dash dipakai sebagai tanda pemisah seperti pada contoh pertama, namun untuk tanda interval setahu Saya memakai – atau N-dash.

https://github.com/ivanlanin/puebi/blob/master/docs/tanda-baca/tanda-pisah.md

**Comment by ivanlanin** [comment]
PUEBI hanya memakai _m-dash_.
